locations:
  work-laptop:
    name: lenovo
    root_dir: /home/dominik/
    trusted: true
    dirs:
      - path: Uni
        exclude_folders:
           - Code/ASOA/Configuration/other/database_backup_architecture_tool/backups/db/
           - Projekte/UNICARagil/Dokumente/00_CONFLUENCE_EXPORT.zip
           - "*/.git/"
      - path: Documents/Bewerbungsunterlagen
        sensitive_folders:
         - Zeugnisse
         - Arbeitszeugnis
      - path: Ectonix
        sensitive_folders:
        - Nextcloud/Vertraulich
      - path: Code
      - path: Desktop
     
  external-hard-drive:
    name: toshiba
    root_dir: /media/veracrypt1
    trusted: true
    dirs:
       - path: Arbeit/Uni
       - path: Arbeit/Bewerbungsunterlagen
         sensitive_folders:
         - Zeugnisse
         - Arbeitszeugnis
       - path: Arbeit/Ectonix
       - path: Arbeit/Code
       - path: Arbeit/Desktop
       - path: Privat
         sensitive_folders:
         - Dokumente/Freiberuflich
         - Dokumente/Gesundheit
         - Dokumente/Lohn
         - Dokumente/Steuer
         - Dokumente/Finanzen

  remote-storagebox:
    name: storagebox
    root_dir: /home
    trusted: false
    dirs:
      - path: Arbeit/Uni
      - path: Arbeit/Bewerbungsunterlagen
        sensitive_folders:
        - Zeugnisse
        - Arbeitszeugnis
      - path: Arbeit/Ectonix
      - path: Arbeit/Code
      - path: Arbeit/Desktop
      - path: Privat
        sensitive_folders:
        - Dokumente/Freiberuflich
        - Dokumente/Gesundheit
        - Dokumente/Lohn
        - Dokumente/Steuer
        - Dokumente/Finanzen/
    ssh:
     username: u425201
     hostname: u425201.your-storagebox.de
     port: 23

gpg:
  recipient: dominik.puellen@uni-passau.de
  tmp_dir: /tmp/synbuddy

